# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: flow/entities/account.proto, flow/entities/block.proto, flow/entities/block_execution_data.proto, flow/entities/block_header.proto, flow/entities/block_seal.proto, flow/entities/collection.proto, flow/entities/event.proto, flow/entities/execution_result.proto, flow/entities/execution_state.proto, flow/entities/metadata.proto, flow/entities/node_version_info.proto, flow/entities/register.proto, flow/entities/transaction.proto
# plugin: python-betterproto
# This file has been @generated
import warnings
from dataclasses import dataclass
from datetime import datetime
from typing import (
    Dict,
    List,
)

import betterproto


class BlockStatus(betterproto.Enum):
    BLOCK_UNKNOWN = 0
    BLOCK_FINALIZED = 1
    BLOCK_SEALED = 2


class EventEncodingVersion(betterproto.Enum):
    JSON_CDC_V0 = 0
    CCF_V0 = 1


class TransactionStatus(betterproto.Enum):
    UNKNOWN = 0
    PENDING = 1
    FINALIZED = 2
    EXECUTED = 3
    SEALED = 4
    EXPIRED = 5


@dataclass(eq=False, repr=False)
class Account(betterproto.Message):
    address: bytes = betterproto.bytes_field(1)
    balance: int = betterproto.uint64_field(2)
    code: bytes = betterproto.bytes_field(3)
    keys: List["AccountKey"] = betterproto.message_field(4)
    contracts: Dict[str, bytes] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_BYTES
    )


@dataclass(eq=False, repr=False)
class AccountKey(betterproto.Message):
    index: int = betterproto.uint32_field(1)
    public_key: bytes = betterproto.bytes_field(2)
    sign_algo: int = betterproto.uint32_field(3)
    hash_algo: int = betterproto.uint32_field(4)
    weight: int = betterproto.uint32_field(5)
    sequence_number: int = betterproto.uint32_field(6)
    revoked: bool = betterproto.bool_field(7)


@dataclass(eq=False, repr=False)
class BlockHeader(betterproto.Message):
    id: bytes = betterproto.bytes_field(1)
    parent_id: bytes = betterproto.bytes_field(2)
    height: int = betterproto.uint64_field(3)
    timestamp: datetime = betterproto.message_field(4)
    payload_hash: bytes = betterproto.bytes_field(5)
    view: int = betterproto.uint64_field(6)
    parent_voter_ids: List[bytes] = betterproto.bytes_field(7)
    parent_voter_sig_data: bytes = betterproto.bytes_field(8)
    proposer_id: bytes = betterproto.bytes_field(9)
    proposer_sig_data: bytes = betterproto.bytes_field(10)
    chain_id: str = betterproto.string_field(11)
    parent_voter_indices: bytes = betterproto.bytes_field(12)
    last_view_tc: "TimeoutCertificate" = betterproto.message_field(13)
    parent_view: int = betterproto.uint64_field(14)


@dataclass(eq=False, repr=False)
class TimeoutCertificate(betterproto.Message):
    view: int = betterproto.uint64_field(1)
    high_qc_views: List[int] = betterproto.uint64_field(2)
    highest_qc: "QuorumCertificate" = betterproto.message_field(3)
    signer_indices: bytes = betterproto.bytes_field(4)
    sig_data: bytes = betterproto.bytes_field(5)


@dataclass(eq=False, repr=False)
class QuorumCertificate(betterproto.Message):
    view: int = betterproto.uint64_field(1)
    block_id: bytes = betterproto.bytes_field(2)
    signer_indices: bytes = betterproto.bytes_field(3)
    sig_data: bytes = betterproto.bytes_field(4)


@dataclass(eq=False, repr=False)
class Collection(betterproto.Message):
    id: bytes = betterproto.bytes_field(1)
    transaction_ids: List[bytes] = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class CollectionGuarantee(betterproto.Message):
    collection_id: bytes = betterproto.bytes_field(1)
    signatures: List[bytes] = betterproto.bytes_field(2)
    reference_block_id: bytes = betterproto.bytes_field(3)
    signature: bytes = betterproto.bytes_field(4)
    signer_ids: List[bytes] = betterproto.bytes_field(5)
    signer_indices: bytes = betterproto.bytes_field(6)
    cluster_chain_id: bytes = betterproto.bytes_field(7)


@dataclass(eq=False, repr=False)
class BlockSeal(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)
    execution_receipt_id: bytes = betterproto.bytes_field(2)
    execution_receipt_signatures: List[bytes] = betterproto.bytes_field(3)
    result_approval_signatures: List[bytes] = betterproto.bytes_field(4)
    final_state: bytes = betterproto.bytes_field(5)
    result_id: bytes = betterproto.bytes_field(6)
    aggregated_approval_sigs: List["AggregatedSignature"] = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class AggregatedSignature(betterproto.Message):
    verifier_signatures: List[bytes] = betterproto.bytes_field(1)
    signer_ids: List[bytes] = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class ExecutionResult(betterproto.Message):
    previous_result_id: bytes = betterproto.bytes_field(1)
    block_id: bytes = betterproto.bytes_field(2)
    chunks: List["Chunk"] = betterproto.message_field(3)
    service_events: List["ServiceEvent"] = betterproto.message_field(4)
    execution_data_id: bytes = betterproto.bytes_field(5)


@dataclass(eq=False, repr=False)
class Chunk(betterproto.Message):
    collection_index: int = betterproto.uint32_field(1)
    start_state: bytes = betterproto.bytes_field(2)
    event_collection: bytes = betterproto.bytes_field(3)
    block_id: bytes = betterproto.bytes_field(4)
    total_computation_used: int = betterproto.uint64_field(5)
    number_of_transactions: int = betterproto.uint32_field(6)
    index: int = betterproto.uint64_field(7)
    end_state: bytes = betterproto.bytes_field(8)
    execution_data_id: bytes = betterproto.bytes_field(9)
    state_delta_commitment: bytes = betterproto.bytes_field(10)
    """
    use. This representation has less surface for byzantine nodes to create
    data inconsistencies compared to the `execution_data_id` being included at
    the ExecutionResult's root level.
    """

    service_event_count: int = betterproto.uint32_field(11)


@dataclass(eq=False, repr=False)
class ServiceEvent(betterproto.Message):
    type: str = betterproto.string_field(1)
    payload: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class ExecutionReceiptMeta(betterproto.Message):
    executor_id: bytes = betterproto.bytes_field(1)
    result_id: bytes = betterproto.bytes_field(2)
    spocks: List[bytes] = betterproto.bytes_field(3)
    executor_signature: bytes = betterproto.bytes_field(4)


@dataclass(eq=False, repr=False)
class ExecutionReceipt(betterproto.Message):
    meta: "ExecutionReceiptMeta" = betterproto.message_field(1)
    execution_result: "ExecutionResult" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Block(betterproto.Message):
    id: bytes = betterproto.bytes_field(1)
    parent_id: bytes = betterproto.bytes_field(2)
    height: int = betterproto.uint64_field(3)
    timestamp: datetime = betterproto.message_field(4)
    collection_guarantees: List["CollectionGuarantee"] = betterproto.message_field(5)
    block_seals: List["BlockSeal"] = betterproto.message_field(6)
    signatures: List[bytes] = betterproto.bytes_field(7)
    execution_receipt_meta_list: List["ExecutionReceiptMeta"] = (
        betterproto.message_field(8)
    )
    execution_result_list: List["ExecutionResult"] = betterproto.message_field(9)
    block_header: "BlockHeader" = betterproto.message_field(10)
    protocol_state_id: bytes = betterproto.bytes_field(11)


@dataclass(eq=False, repr=False)
class Event(betterproto.Message):
    type: str = betterproto.string_field(1)
    transaction_id: bytes = betterproto.bytes_field(2)
    transaction_index: int = betterproto.uint32_field(3)
    event_index: int = betterproto.uint32_field(4)
    payload: bytes = betterproto.bytes_field(5)


@dataclass(eq=False, repr=False)
class ExecutionStateQuery(betterproto.Message):
    """
    ExecutionStateQuery defines the criteria to use when selecting the
    ExecutionResult to use for the requested data.
    """

    agreeing_executors_count: int = betterproto.uint64_field(1)
    """Minimum number of execution receipts for the execution result."""

    required_executor_ids: List[bytes] = betterproto.bytes_field(2)
    """
    Set of execution node IDs, one of which must have produced the execution
    result.
    """

    include_executor_metadata: bool = betterproto.bool_field(3)
    """Whether or not to include ExecutorMetadata in the response."""


@dataclass(eq=False, repr=False)
class ExecutorMetadata(betterproto.Message):
    """
    ExecutorMetadata contains data about the execution result used to serve the
    request.
    """

    execution_result_id: bytes = betterproto.bytes_field(1)
    """ID of the ExecutionResult used to serve the request"""

    executor_ids: List[bytes] = betterproto.bytes_field(2)
    """Node IDs of Execution nodes that produced the result"""


@dataclass(eq=False, repr=False)
class Metadata(betterproto.Message):
    """
    Metadata contains data about the node's state at the time of the request.
    """

    latest_finalized_block_id: bytes = betterproto.bytes_field(1)
    """Block ID of the latest finalized block"""

    latest_finalized_height: int = betterproto.uint64_field(2)
    """Height of the latest finalized block"""

    node_id: bytes = betterproto.bytes_field(3)
    """Node's unique ID"""

    highest_indexed_height: int = betterproto.uint64_field(4)
    """
    Height of the latest block who's execution state data is fully indexed
    """

    executor_metadata: "ExecutorMetadata" = betterproto.message_field(5)
    """Metadata about the execution result used to serve the request."""


@dataclass(eq=False, repr=False)
class CompatibleRange(betterproto.Message):
    start_height: int = betterproto.uint64_field(1)
    """The first block that the version supports."""

    end_height: int = betterproto.uint64_field(2)
    """The last block that the version supports."""


@dataclass(eq=False, repr=False)
class NodeVersionInfo(betterproto.Message):
    semver: str = betterproto.string_field(1)
    """The currently running node software version."""

    commit: str = betterproto.string_field(2)
    """The git commit hash of the currently running node software."""

    spork_id: bytes = betterproto.bytes_field(3)
    """
    The unique identifier for the node's network within the current spork.
    """

    protocol_version: int = betterproto.uint64_field(4)
    """
    The deprecated protocol version number. Previously this referred to the
    major software version as of the most recent spork. Replaced by
    protocol_state_version.
    """

    spork_root_block_height: int = betterproto.uint64_field(5)
    """
    The spork root block height. This is the height of the first sealed block
    in the spork network.
    """

    node_root_block_height: int = betterproto.uint64_field(6)
    """
    The node's root block height. This is the first sealed block in the node's
    protocol database. If the node started at the beginning of the spork, it is
    the same as the spork root block height. If the node started after the
    beginning of the spork, it is the height of the first sealed block indexed.
    """

    compatible_range: "CompatibleRange" = betterproto.message_field(7)
    """The compatible version range."""

    protocol_state_version: int = betterproto.uint64_field(8)
    """
    The Protocol State version as of the latest finalized block. This tracks
    the schema version of the Protocol State and is used to coordinate breaking
    changes in the Protocol. Version numbers are monotonically increasing.
    """

    def __post_init__(self) -> None:
        super().__post_init__()
        if self.is_set("protocol_version"):
            warnings.warn(
                "NodeVersionInfo.protocol_version is deprecated", DeprecationWarning
            )


@dataclass(eq=False, repr=False)
class Transaction(betterproto.Message):
    script: bytes = betterproto.bytes_field(1)
    arguments: List[bytes] = betterproto.bytes_field(2)
    reference_block_id: bytes = betterproto.bytes_field(3)
    gas_limit: int = betterproto.uint64_field(4)
    proposal_key: "TransactionProposalKey" = betterproto.message_field(5)
    payer: bytes = betterproto.bytes_field(6)
    authorizers: List[bytes] = betterproto.bytes_field(7)
    payload_signatures: List["TransactionSignature"] = betterproto.message_field(8)
    envelope_signatures: List["TransactionSignature"] = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class TransactionProposalKey(betterproto.Message):
    address: bytes = betterproto.bytes_field(1)
    key_id: int = betterproto.uint32_field(2)
    sequence_number: int = betterproto.uint64_field(3)


@dataclass(eq=False, repr=False)
class TransactionSignature(betterproto.Message):
    address: bytes = betterproto.bytes_field(1)
    key_id: int = betterproto.uint32_field(2)
    signature: bytes = betterproto.bytes_field(3)
    extension_data: bytes = betterproto.bytes_field(4)


@dataclass(eq=False, repr=False)
class BlockExecutionData(betterproto.Message):
    """
    BlockExecutionData represents the collection of data produced while
    execiting the block.
    """

    block_id: bytes = betterproto.bytes_field(1)
    """Block ID of the block that was executed."""

    chunk_execution_data: List["ChunkExecutionData"] = betterproto.message_field(2)
    """
    Ordered list of ChunkExecutionData produced while executing the block.
    Note: there will be one ChunkExecutionData per collection in the block,
    plus one for the service chunk. The service chunk is executed last and is
    always the last chunk in the list.
    """


@dataclass(eq=False, repr=False)
class ChunkExecutionData(betterproto.Message):
    """
    ChunkExecutionData represents the collection of data produced while
    executing a chunk.
    """

    collection: "ExecutionDataCollection" = betterproto.message_field(1)
    """
    Ordered list of transactions included in the collection that was executed
    in the chunk.
    """

    events: List["Event"] = betterproto.message_field(2)
    """
    Events emitted by transactions in the collection. Note: events listed in
    the last ChunkExecutionData in the BlockExecutionData were emitted by the
    service transaction. Some, but not all, of these events are service events.
    """

    trie_update: "TrieUpdate" = betterproto.message_field(3)
    """
    TrieUpdate produced by executing the collection. TrieUpdates contain a list
    of registers that were modified during chunk execution. The value included
    is the new value of the register.
    """

    transaction_results: List["ExecutionDataTransactionResult"] = (
        betterproto.message_field(4)
    )
    """
    Transaction results produced by executing the collection. Note: these are
    not the same type of results returned by other RPCs. These results are
    sepcific to execution data. The most notable difference is they only
    include a boolean value to indicate whether or not an error was encountered
    during execution, not the error itself.
    """


@dataclass(eq=False, repr=False)
class ExecutionDataCollection(betterproto.Message):
    """
    ExecutionDataCollection represents the collection of transactions that were
    executed within a chunk. Note: this is not the same type as the
    entities.Collection.
    """

    transactions: List["Transaction"] = betterproto.message_field(1)
    """List of transactions included in the collection."""


@dataclass(eq=False, repr=False)
class TrieUpdate(betterproto.Message):
    """
    TrieUpdate produced by executing the collection. TrieUpdates contain a list
    of registers that were modified during chunk execution. The value included
    is the new value of the register.
    """

    root_hash: bytes = betterproto.bytes_field(1)
    """RootHash is the root hash of the trie before the update is applied."""

    paths: List[bytes] = betterproto.bytes_field(2)
    """
    List of register paths updated. Note: paths and payloads map 1:1 with
    eachother. i.e. for each element in path, the value in payloads at the same
    index is the value of the register at that path.
    """

    payloads: List["Payload"] = betterproto.message_field(3)
    """
    List of register values updated. Note: paths and payloads map 1:1 with
    eachother. i.e. for each element in path, the value in payloads at the same
    index is the value of the register at that path.
    """


@dataclass(eq=False, repr=False)
class Payload(betterproto.Message):
    """Payload represents the key-value pair of a register."""

    key_part: List["KeyPart"] = betterproto.message_field(1)
    """
    List of key parts that make up the register key. Can be converted into
    register id.
    """

    value: bytes = betterproto.bytes_field(2)
    """Value of the register."""


@dataclass(eq=False, repr=False)
class KeyPart(betterproto.Message):
    """KeyPart represents a part of a register key."""

    type: int = betterproto.uint32_field(1)
    """Type of the key part."""

    value: bytes = betterproto.bytes_field(2)
    """Value of the key part."""


@dataclass(eq=False, repr=False)
class ExecutionDataTransactionResult(betterproto.Message):
    """
    ExecutionDataTransactionResult represents the result of executing a
    transaction.
    """

    transaction_id: bytes = betterproto.bytes_field(1)
    """Transaction ID of the transaction that was executed."""

    failed: bool = betterproto.bool_field(2)
    """
    Boolean indicating whether or not the transaction's execution failed with
    an error.
    """

    computation_used: int = betterproto.uint64_field(3)
    """Amount of computation used during execution."""


@dataclass(eq=False, repr=False)
class RegisterId(betterproto.Message):
    owner: bytes = betterproto.bytes_field(1)
    key: bytes = betterproto.bytes_field(2)
